"""Removed cash

Revision ID: c27a0ac2bcfe
Revises: 841478ad2921
Create Date: 2023-02-23 06:08:28.715901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c27a0ac2bcfe'
down_revision = '841478ad2921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
